services:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80" 

    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

# Database 
  database:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - ./database/.env
    volumes:
      - database:/data/db
    restart: unless-stopped

# Adminer UI
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8081:8080"
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy

# Backend FastAPI
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./backend/.env
      - ./rabbitmq/.env
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend/prompts:/app/backend/prompts
    restart: unless-stopped

 # RabbitMQ (with admin web UI)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  # Preprocess async woker
  preprocess:
    container_name: preprocess
    build:
      context: .   
      dockerfile: workers/preprocess/Dockerfile
    env_file:
      - ./rabbitmq/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./backend/data:/app/backend/data  
    restart: unless-stopped
  
  # Format async worker
  format:
    container_name: format
    build:
      context: .  
      dockerfile: workers/format/Dockerfile
    env_file:
      - ./workers/format/.env
      - ./rabbitmq/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./backend/data:/app/backend/data  
    restart: unless-stopped
  
  # Prompt async worker
  prompt:
    container_name: prompt
    build:
      context: .  
      dockerfile: workers/prompt/Dockerfile
    env_file:
      - ./workers/format/.env
      - ./rabbitmq/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./backend/prompts:/app/backend/prompts
    restart: unless-stopped

  # Vectorize async worker
  vectorize:
    container_name: vectorize
    build:
      context: .  
      dockerfile: workers/vectorize/Dockerfile
    env_file:
      - ./workers/vectorize/.env
      - ./rabbitmq/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./backend/data:/app/backend/data  
      - ./workers/vectorize/databases:/app/databases
    restart: unless-stopped

  # 
  barriers:
    container_name: barriers
    build:
      context: .  
      dockerfile: barriers/Dockerfile
    env_file:
      - ./rabbitmq/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  # Deploy async worker
  deploy:
    container_name: deploy
    build:
      context: .  
      dockerfile: workers/deploy/Dockerfile
    env_file:
      - ./rabbitmq/.env
      - ./workers/vectorize/.env
      - ./workers/deploy/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./workers/vectorize/databases:/app/databases
      - ./backend/prompts:/app/prompts
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  # Agent base 
  agent-base:
    build:
      context: .  
      dockerfile: workers/deploy/templates/Dockerfile
    env_file:
      - ./workers/vectorize/.env
    image: agent-base
    
# Volumes
volumes:
  database:
    driver: local
  
